
-- 启用 UUID 扩展
create extension if not exists "uuid-ossp";

-- 1. 创建 Settings 表
create table public.settings (
  id bigint generated by default as identity primary key,
  "maxSlotsPerBarberPerDay" integer not null default 10,
  "openingTime" text not null default '08:00',
  "closingTime" text not null default '17:00',
  "slotDurationMinutes" integer not null default 45,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 插入默认设置 (确保 ID 为 1)
insert into public.settings (id, "maxSlotsPerBarberPerDay", "openingTime", "closingTime", "slotDurationMinutes")
values (1, 10, '08:00', '17:00', 45)
on conflict (id) do nothing;

-- 2. 创建 Barbers 表
create table public.barbers (
  id text primary key,
  name text not null,
  specialty text,
  "avatarUrl" text,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 插入默认理发师数据
insert into public.barbers (id, name, specialty, "avatarUrl", bio)
values 
  ('b1', 'Alex "The Fade" Miller', '渐变 & 现代剪裁', 'https://picsum.photos/100/100?random=1', '擅长皮肤渐变和纹理处理。'),
  ('b2', 'Sarah Scissors', '长发 & 造型', 'https://picsum.photos/100/100?random=2', '拥有10年复杂层次剪裁经验。'),
  ('b3', 'Davide Classic', '胡须 & 经典剪裁', 'https://picsum.photos/100/100?random=3', '融合现代风格的老派技术。')
on conflict (id) do nothing;

-- 3. 创建 Appointments 表
create table public.appointments (
  id text primary key, -- 使用 UUID 字符串
  "barberId" text not null references public.barbers(id),
  "userId" text not null,
  "userName" text,
  "customerName" text, -- 新增: 客户填写姓名
  "customerPhone" text, -- 新增: 客户填写电话
  date text not null, -- 格式: YYYY-MM-DD
  "timeSlot" text not null, -- 格式: HH:mm
  status text not null, -- BOOKED, COMPLETED, CANCELLED
  timestamp bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. 创建 Logs 表
create table public.logs (
  id text primary key,
  action text not null,
  details text,
  timestamp bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. 创建 Users 表
create table public.users (
  id text primary key,
  username text not null unique,
  password text, -- 允许为空 (微信登录用户可能没有初始密码)
  name text,
  phone text,
  role text not null default 'USER',
  "avatarUrl" text,
  "wechatId" text unique, -- 新增: 微信 OpenID
  "createdAt" bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 插入默认管理员 (DB模式)
insert into public.users (id, username, password, name, phone, role, "createdAt")
values ('admin_001', 'admin', 'admin123', '系统管理员', '13800000000', 'ADMIN', extract(epoch from now()) * 1000)
on conflict (username) do nothing;

-- 设置行级安全策略 (RLS)
-- 注意：为了演示方便，这里允许公开读写。在生产环境中应配置更严格的 Auth 策略。

alter table public.settings enable row level security;
alter table public.barbers enable row level security;
alter table public.appointments enable row level security;
alter table public.logs enable row level security;
alter table public.users enable row level security;

-- Settings 策略
create policy "Enable read access for all users" on public.settings for select using (true);
create policy "Enable update access for all users" on public.settings for update using (true);
create policy "Enable insert access for all users" on public.settings for insert with check (true);

-- Barbers 策略
create policy "Enable read access for all users" on public.barbers for select using (true);
create policy "Enable insert/update for all users" on public.barbers for all using (true);

-- Appointments 策略
create policy "Enable read access for all users" on public.appointments for select using (true);
create policy "Enable insert access for all users" on public.appointments for insert with check (true);
create policy "Enable update access for all users" on public.appointments for update using (true);

-- Logs 策略
create policy "Enable read access for all users" on public.logs for select using (true);
create policy "Enable insert access for all users" on public.logs for insert with check (true);

-- Users 策略
create policy "Enable read access for all users" on public.users for select using (true);
create policy "Enable insert access for all users" on public.users for insert with check (true);
create policy "Enable update access for all users" on public.users for update using (true);
